#include "qcrate_runtime_config.h"

#define QCRATE_CONFIG_MAX_FRAME_WORDS UINT32_C(262144)
#define QCRATE_CONFIG_MAX_FRAMES      UINT32_C(255)
#define QCRATE_CONFIG_MAX_TOTAL_WORDS UINT32_C(1000000)

uint32_t qcrate_validate_runtime_config(const uint32_t *words)
{
	uint64_t config_id;
	uint64_t total_words;

	config_id = ((uint64_t)words[QCRATE_CONFIG_ID_HIGH_WORD] << 32U) |
		words[QCRATE_CONFIG_ID_LOW_WORD];
	if (config_id == 0U)
		return QCRATE_CONFIG_REASON_ZERO_ID;
	if ((words[QCRATE_CONFIG_SIGNAL_AMPLITUDE_WORD] &
	     UINT32_C(0xFFFF0000)) != 0U ||
	    words[QCRATE_CONFIG_SIGNAL_AMPLITUDE_WORD] > UINT32_C(0x7FFF))
		return QCRATE_CONFIG_REASON_SIGNAL_AMPLITUDE;
	if ((words[QCRATE_CONFIG_NOISE_AMPLITUDE_WORD] &
	     UINT32_C(0xFFFF0000)) != 0U ||
	    words[QCRATE_CONFIG_NOISE_AMPLITUDE_WORD] > UINT32_C(0x7FFF))
		return QCRATE_CONFIG_REASON_NOISE_AMPLITUDE;
	if (words[QCRATE_CONFIG_SIGNAL_AMPLITUDE_WORD] +
	    words[QCRATE_CONFIG_NOISE_AMPLITUDE_WORD] > UINT32_C(0x8000))
		return QCRATE_CONFIG_REASON_AMPLITUDE_SUM;
	if ((words[QCRATE_CONFIG_NOISE_SEED_WORD] &
	     UINT32_C(0xFFFF0000)) != 0U ||
	    words[QCRATE_CONFIG_NOISE_SEED_WORD] == 0U)
		return QCRATE_CONFIG_REASON_ZERO_NOISE_SEED;
	if (words[QCRATE_CONFIG_FRAME_LENGTH_WORD] == 0U ||
	    words[QCRATE_CONFIG_FRAME_LENGTH_WORD] >
	    QCRATE_CONFIG_MAX_FRAME_WORDS)
		return QCRATE_CONFIG_REASON_FRAME_LENGTH;
	if (words[QCRATE_CONFIG_FRAME_COUNT_WORD] == 0U ||
	    words[QCRATE_CONFIG_FRAME_COUNT_WORD] > QCRATE_CONFIG_MAX_FRAMES)
		return QCRATE_CONFIG_REASON_FRAME_COUNT;
	total_words = (uint64_t)words[QCRATE_CONFIG_FRAME_LENGTH_WORD] *
		words[QCRATE_CONFIG_FRAME_COUNT_WORD];
	if (total_words > QCRATE_CONFIG_MAX_TOTAL_WORDS)
		return QCRATE_CONFIG_REASON_TOTAL_WORDS;
	return QCRATE_CONFIG_REASON_NONE;
}
