#!/usr/bin/env python3
"""Reproducible Vivado build orchestrator for Q-Crate."""
from __future__ import annotations

import argparse
import json
import shlex
import shutil
import subprocess
import sys
from pathlib import Path
from typing import NoReturn

STAGES = ("project", "synth", "impl", "bitstream", "xsa", "export", "all")
RTL_SUFFIXES = {".v", ".sv", ".vh", ".svh"}
DATA_SUFFIXES = {".coe", ".hex", ".mem"}


def die(message: str) -> NoReturn:
    print(f"error: {message}", file=sys.stderr)
    raise SystemExit(2)


def repo_root(start: Path) -> Path:
    for path in (start.resolve(), *start.resolve().parents):
        if (
            (path / "config").is_dir()
            and (path / "scripts" / "build.py").is_file()
            and (path / "kv260" / "hw").is_dir()
        ):
            return path
    die("run this command inside the Q-Crate repository")


def resolve(root: Path, value: str) -> Path:
    path = Path(value)
    return path.resolve() if path.is_absolute() else (root / path).resolve()


def discover(root: Path, directories: list[str], suffixes: set[str]) -> list[Path]:
    files: list[Path] = []
    for item in directories:
        directory = resolve(root, item)
        if not directory.exists():
            print(f"warning: missing directory: {directory}")
            continue
        files += [
            p.resolve() for p in directory.rglob("*")
            if p.is_file() and p.suffix.lower() in suffixes
        ]
    return sorted(set(files))


def tq(value: str | Path) -> str:
    text = str(value).replace("\\", "/")
    if "{" in text or "}" in text:
        die(f"unsupported brace in Tcl value: {text}")
    return "{" + text + "}"


def tcl_list_assignment(name: str, values: list[str | Path]) -> list[str]:
    if not values:
        return [f"set {name} [list]"]
    return [
        f"set {name} [list \\",
        *[f"  {tq(path)} \\" for path in values[:-1]],
        f"  {tq(values[-1])}]",
    ]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="config/build.json")
    parser.add_argument("--stage", choices=STAGES, default="project")
    parser.add_argument("--define", action="append", default=[],
                        help="Verilog/SystemVerilog macro for synthesis; may be repeated")
    parser.add_argument("--vivado")
    parser.add_argument("--clean", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    root = repo_root(Path.cwd())
    config_path = resolve(root, args.config)
    if not config_path.is_file():
        die("create config/build.json or pass --config")
    try:
        cfg = json.loads(config_path.read_text())
    except json.JSONDecodeError as exc:
        die(f"invalid JSON in {config_path}: {exc}")

    required = ["project_name", "top", "part", "bd_tcl", "rtl_dirs",
                "xdc_dirs", "build_dir", "artifact_dir", "jobs", "vivado"]
    missing = [key for key in required if key not in cfg]
    if missing:
        die(f"missing config keys: {', '.join(missing)}")

    build_dir = resolve(root, cfg["build_dir"])
    artifact_dir = resolve(root, cfg["artifact_dir"])
    if args.clean:
        for directory in (build_dir, artifact_dir):
            if directory.exists():
                print(f"removing {directory}")
                shutil.rmtree(directory)
        return 0

    bd_tcl = resolve(root, cfg["bd_tcl"])
    if not bd_tcl.is_file():
        die(f"missing exported BD Tcl: {bd_tcl}")

    rtl = discover(root, cfg["rtl_dirs"], RTL_SUFFIXES)
    data = discover(root, cfg.get("data_dirs", []), DATA_SUFFIXES)
    xdc = discover(root, cfg["xdc_dirs"], {".xdc"})
    if not rtl:
        die("no RTL files discovered")
    for define in args.define:
        if not define:
            die("--define cannot be empty")

    manifest = build_dir / "generated" / "build_manifest.tcl"
    manifest.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by scripts/build.py; do not commit.",
        f"set cfg_project_name {tq(cfg['project_name'])}",
        f"set cfg_top {tq(cfg['top'])}",
        f"set cfg_part {tq(cfg['part'])}",
        f"set cfg_board_part {tq(cfg.get('board_part', ''))}",
        f"set cfg_build_dir {tq(build_dir)}",
        f"set cfg_artifact_dir {tq(artifact_dir)}",
        f"set cfg_bd_tcl {tq(bd_tcl)}",
        f"set cfg_jobs {int(cfg['jobs'])}",
        *tcl_list_assignment("cfg_verilog_defines", args.define),
        *tcl_list_assignment("cfg_rtl_files", rtl),
        *tcl_list_assignment("cfg_data_files", data),
        *tcl_list_assignment("cfg_xdc_files", xdc),
    ]
    manifest.write_text("\n".join(lines) + "\n")

    vivado = args.vivado or cfg["vivado"]
    vivado_settings = cfg.get("vivado_settings", "")
    tcl = root / "scripts" / "vivado_build.tcl"
    vivado_args = [vivado, "-mode", "batch", "-nojournal", "-nolog",
                   "-source", str(tcl), "-tclargs", str(manifest), args.stage]

    print(f"BD Tcl    : {bd_tcl}")
    print(f"RTL files : {len(rtl)}")
    print(f"Data files: {len(data)}")
    print(f"XDC files : {len(xdc)}")
    if args.define:
        print("defines   :", " ".join(args.define))
    print(f"stage     : {args.stage}")
    if vivado_settings:
        print("command   :", "source", shlex.quote(vivado_settings), "&&",
              " ".join(shlex.quote(item) for item in vivado_args))
    else:
        print("command   :", " ".join(shlex.quote(item) for item in vivado_args))
    if args.dry_run:
        return 0

    if vivado_settings and not Path(vivado_settings).is_file():
        die(f"missing Vivado settings script: {vivado_settings}")
    if not vivado_settings and shutil.which(vivado) is None and not Path(vivado).is_file():
        die("Vivado not found; set vivado_settings or pass --vivado")

    artifact_dir.mkdir(parents=True, exist_ok=True)
    if vivado_settings:
        command = [
            "bash", "-lc",
            'source "$1" && shift && exec "$@"',
            "vivado-env", vivado_settings, *vivado_args,
        ]
    else:
        command = vivado_args
    result = subprocess.run(command, cwd=root, check=False)
    if result.returncode:
        die(f"Vivado exited with code {result.returncode}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
